name: threat-oracle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.0
  - nodejs=18
  - npm
  - fastapi=0.104.1
  - uvicorn=0.23.2
  - pydantic=2.4.2
  - python-dotenv=1.0.0
  - pytest=7.4.3
  - pytest-cov=4.1.0
  - black=23.10.1
  - pip:
    - neo4j==5.14.0
    - httpx==0.25.0
    - ruff==0.1.3
    - mypy==1.6.1
    - pre-commit==3.5.0
    - pydantic-settings==2.0.3
