name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -r requirements.txt
      - name: Lint with pre-commit
        run: pre-commit run --all-files

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd src/frontend
          npm ci
      - name: Test with npm
        run: |
          cd src/frontend
          npm test

  check-user-approval:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check for user approval
        run: |
          # Check if INTERACTION_LOG.md exists
          if [ ! -f "INTERACTION_LOG.md" ]; then
            echo "Error: INTERACTION_LOG.md does not exist."
            exit 1
          fi
          
          # Check for user approval in INTERACTION_LOG.md
          if ! grep -iE "feature set approved|user approval|approved by user" INTERACTION_LOG.md; then
            echo "Error: No user approval found in INTERACTION_LOG.md."
            echo "Please demonstrate the feature to the user and get their approval before creating a PR."
            echo "The approval should be documented in the interaction log with phrases like:"
            echo "  - 'feature set approved'"
            echo "  - 'user approval'"
            echo "  - 'approved by user'"
            exit 1
          fi
          
          echo "User approval found in interaction log."
